### ISSUE TITLE
Add support for scouting

### ISSUE THREAD

**Issue by jonathan-hepp** [eclipse-zenoh/zenoh-kotlin#138]
### Describe the feature

The Kotlin library lacks some of the features available in the Rust and Python ones. Scouting is an important feature that is currently not supported and is fundamental to fully take advantage of Zenoh. I'd like to know if there are any plans to implement this or if there is some history as to why this isn't available yet. I would be happy to help if given some guidance on the topic.

**Comment by DariusIMP** [comment]
I'll be adding this as soon as possible, the release in September will include this.
