### ISSUE TITLE
[Bug] JVM crashes when attempting to garbage collect a session that wasn't properly initialized 

### ISSUE THREAD

**Issue by jonathan-hepp** [eclipse-zenoh/zenoh-kotlin#139]
### Describe the bug

During finalization of the Session object, close() is called on a JNISession for which the open() method did not succeed, resulting in a JVM crash

### To reproduce

1. Attempt to open a Session with invalid credentials or any invalid config that results in a SessionException
2. Wait for GC to run
3. JVM crashes with a SIGSEGV

### System info

- Platform: Linux 6.5.0-44-generic, Ubuntu 22.04.1, x86_64
- Zehoh version: 0.11.0

**Comment by DariusIMP** [comment]
Closing issue since the fix from https://github.com/eclipse-zenoh/zenoh-kotlin/pull/140 is already merged on main.
