### ISSUE TITLE
[Bug] Scouting task being stopped results in UnsatisfiedLinkError

### ISSUE THREAD

**Issue by hassomehide** [eclipse-zenoh/zenoh-kotlin#202]
### Describe the bug

I am trying to use the newly added scouting feature and it mostly seems to work, however when I attempt to stop the scouting task I get an Error:
```
java.lang.UnsatisfiedLinkError: 'void io.zenoh.jni.JNIScout$Companion.freePtrViaJNI(long)'
	at io.zenoh.jni.JNIScout$Companion.freePtrViaJNI(Native Method)
	at io.zenoh.jni.JNIScout.close(JNIScout.kt:64)
	at io.zenoh.scouting.Scout.stop(Scout.kt:37)
```

### To reproduce

1. `val scout = Zenoh.scout(Channel())`
2. `scout.stop()`

### System info

- ubuntu 24.04, linux kernel 6.8.0-41
- zenoh-kotlin-jvm 1.0.0-beta.1

**Comment by DariusIMP** [comment]
Thanks for reporting this, I have just submitted a fix for this issue. I'm also modifying the api so that when declaring a scout, a `Result<Scout<Receiver>>` is returned, instead of directly a `Scout<Receiver>` as the operation could fail.
