### ISSUE TITLE
[Bug] Unable to load Zenoh JNI after upgrade to 1.0.0-beta.4

### ISSUE THREAD

**Issue by hassomehide** [eclipse-zenoh/zenoh-kotlin#253]
### Describe the bug

After upgrading to 1.0.0-beta.4 I am getting an error:

```
Caused by: java.lang.Exception: Unable to load Zenoh JNI: java.lang.NullPointerException
	at io.zenoh.ZenohLoad.tryLoadingLibraryFromJarPackage-IoAF18A(Zenoh.kt:137)
	at io.zenoh.ZenohLoad.<clinit>(Zenoh.kt:35)
```

Seems to be related to https://github.com/eclipse-zenoh/zenoh-kotlin/pull/250
Not using Spring nor running my application as a JAR. Classloader used by the `javaClass.getResourceAsStream` is `jdk.internal.loader.ClassLoaders.AppClassLoader` according to debugger.

### To reproduce

Do literally anything that triggers loading the native library

### System info

zenoh-kotlin 1.0.0-beta.4

**Comment by DariusIMP** [comment]
Thanks for reporting this. I'm reverting the change until further investigation.
