### ISSUE TITLE
Add the option to fetch the paramters as Map from Selector

### ISSUE THREAD

**Issue by vanny96** [eclipse-zenoh/zenoh-kotlin#64]
### Describe the feature

The rust API for the `Selector` class allows to retrieve the paramaters as a map with the `parameters_map` method. It would be nice to have such a feature in the kotlin API.

This could be implemented either through the JNI, reusing the existing logic used in Rust, or reimplemented in Kotlin using libraries such as `httpcomponents-client`.

Any opinions on this?

**Comment by DariusIMP** [comment]
Hi! Thanks for reporting this, indeed that's one of the features that are missing. There are a couple of other functionalities on the Selector that need to be implemented, I opened issue #67 for that.

> or reimplemented in Kotlin using libraries such as `httpcomponents-client`

I'd rather minimize the reliance on external libs if possible. I haven't yet reviewed your PR, will do so now :)
